[font]
size = 10
[font.normal]
family = "CaskaydiaMono Nerd Font"
style = "Regular"
[font.bold]
family = "CaskaydiaMono Nerd Font"
style = "Bold"
[font.italic]
family = "CaskaydiaMono Nerd Font"
style = "Italic"
[font.bold_italic]
family = "CaskaydiaMono Nerd Font"
style = "Bold Italic"
[window]
padding.x = 8
padding.y = 8
opacity = 0.8
